# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 957cd0d609333b7615ed8b512a04a80ba12460706c6ce88ec565a0f3a225470f5d83424296f191146d651cdd48c730010ab869080f8d3466ffa585fa84eebf29

  telegram:
  # Single bot can be specified like this
    bot:
      token: 283236209:AAGw3KAF7O01mEwr68RaANSh7Pp_-MfuLOY
      username: PartyInDaHouse_bot

test:
  secret_key_base: 9621b65779b2244ee610891e407d7bddc81a242670a2f6e045b92fa805fc067f71e50d15b7f3739ffad6f7f25e0b747986348c99538d93065464c88672de47d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
